// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	models "app-name/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type AssetMod interface {
	Apply(*AssetTemplate)
}

type AssetModFunc func(*AssetTemplate)

func (f AssetModFunc) Apply(n *AssetTemplate) {
	f(n)
}

type AssetModSlice []AssetMod

func (mods AssetModSlice) Apply(n *AssetTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// AssetTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type AssetTemplate struct {
	ID              func() int64
	ConfigurationID func() int64
	ProjectID       func() string
	GlobalAssetID   func() string
	ProviderID      func() string
	AssetID         func() null.Val[int32]

	r assetR
	f *Factory
}

type assetR struct {
	Configuration *assetRConfigurationR
}

type assetRConfigurationR struct {
	o *ConfigurationTemplate
}

// Apply mods to the AssetTemplate
func (o *AssetTemplate) Apply(mods ...AssetMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.Asset
// this does nothing with the relationship templates
func (o AssetTemplate) toModel() *models.Asset {
	m := &models.Asset{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ConfigurationID != nil {
		m.ConfigurationID = o.ConfigurationID()
	}
	if o.ProjectID != nil {
		m.ProjectID = o.ProjectID()
	}
	if o.GlobalAssetID != nil {
		m.GlobalAssetID = o.GlobalAssetID()
	}
	if o.ProviderID != nil {
		m.ProviderID = o.ProviderID()
	}
	if o.AssetID != nil {
		m.AssetID = o.AssetID()
	}

	return m
}

// toModels returns an models.AssetSlice
// this does nothing with the relationship templates
func (o AssetTemplate) toModels(number int) models.AssetSlice {
	m := make(models.AssetSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.Asset
// according to the relationships in the template. Nothing is inserted into the db
func (t AssetTemplate) setModelRels(o *models.Asset) {
	if t.r.Configuration != nil {
		rel := t.r.Configuration.o.toModel()
		rel.R.Assets = append(rel.R.Assets, o)
		o.ConfigurationID = rel.ID
		o.R.Configuration = rel
	}
}

// BuildSetter returns an *models.AssetSetter
// this does nothing with the relationship templates
func (o AssetTemplate) BuildSetter() *models.AssetSetter {
	m := &models.AssetSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.ConfigurationID != nil {
		m.ConfigurationID = omit.From(o.ConfigurationID())
	}
	if o.ProjectID != nil {
		m.ProjectID = omit.From(o.ProjectID())
	}
	if o.GlobalAssetID != nil {
		m.GlobalAssetID = omit.From(o.GlobalAssetID())
	}
	if o.ProviderID != nil {
		m.ProviderID = omit.From(o.ProviderID())
	}
	if o.AssetID != nil {
		m.AssetID = omitnull.FromNull(o.AssetID())
	}

	return m
}

// BuildManySetter returns an []*models.AssetSetter
// this does nothing with the relationship templates
func (o AssetTemplate) BuildManySetter(number int) []*models.AssetSetter {
	m := make([]*models.AssetSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Asset
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AssetTemplate.Create
func (o AssetTemplate) Build() *models.Asset {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.AssetSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AssetTemplate.CreateMany
func (o AssetTemplate) BuildMany(number int) models.AssetSlice {
	m := make(models.AssetSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAsset(m *models.AssetSetter) {
	if m.ProjectID.IsUnset() {
		m.ProjectID = omit.From(random_string(nil))
	}
	if m.GlobalAssetID.IsUnset() {
		m.GlobalAssetID = omit.From(random_string(nil))
	}
	if m.ProviderID.IsUnset() {
		m.ProviderID = omit.From(random_string(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Asset
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *AssetTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Asset) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a asset and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *AssetTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Asset, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a asset and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *AssetTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Asset {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a asset and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *AssetTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Asset {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a asset and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *AssetTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.Asset, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAsset(opt)

	var rel0 *models.Configuration
	if o.r.Configuration == nil {
		var ok bool
		rel0, ok = configurationCtx.Value(ctx)
		if !ok {
			AssetMods.WithNewConfiguration().Apply(o)
		}
	}
	if o.r.Configuration != nil {
		ctx, rel0, err = o.r.Configuration.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}
	opt.ConfigurationID = omit.From(rel0.ID)

	m, err := models.Assets.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = assetCtx.WithValue(ctx, m)

	m.R.Configuration = rel0

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple assets and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o AssetTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.AssetSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple assets and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o AssetTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.AssetSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple assets and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o AssetTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.AssetSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple assets and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o AssetTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.AssetSlice, error) {
	var err error
	m := make(models.AssetSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// Asset has methods that act as mods for the AssetTemplate
var AssetMods assetMods

type assetMods struct{}

func (m assetMods) RandomizeAllColumns(f *faker.Faker) AssetMod {
	return AssetModSlice{
		AssetMods.RandomID(f),
		AssetMods.RandomConfigurationID(f),
		AssetMods.RandomProjectID(f),
		AssetMods.RandomGlobalAssetID(f),
		AssetMods.RandomProviderID(f),
		AssetMods.RandomAssetID(f),
	}
}

// Set the model columns to this value
func (m assetMods) ID(val int64) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m assetMods) IDFunc(f func() int64) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m assetMods) UnsetID() AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m assetMods) RandomID(f *faker.Faker) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m assetMods) ConfigurationID(val int64) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ConfigurationID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m assetMods) ConfigurationIDFunc(f func() int64) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ConfigurationID = f
	})
}

// Clear any values for the column
func (m assetMods) UnsetConfigurationID() AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ConfigurationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m assetMods) RandomConfigurationID(f *faker.Faker) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ConfigurationID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m assetMods) ProjectID(val string) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ProjectID = func() string { return val }
	})
}

// Set the Column from the function
func (m assetMods) ProjectIDFunc(f func() string) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ProjectID = f
	})
}

// Clear any values for the column
func (m assetMods) UnsetProjectID() AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ProjectID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m assetMods) RandomProjectID(f *faker.Faker) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ProjectID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m assetMods) GlobalAssetID(val string) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.GlobalAssetID = func() string { return val }
	})
}

// Set the Column from the function
func (m assetMods) GlobalAssetIDFunc(f func() string) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.GlobalAssetID = f
	})
}

// Clear any values for the column
func (m assetMods) UnsetGlobalAssetID() AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.GlobalAssetID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m assetMods) RandomGlobalAssetID(f *faker.Faker) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.GlobalAssetID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m assetMods) ProviderID(val string) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ProviderID = func() string { return val }
	})
}

// Set the Column from the function
func (m assetMods) ProviderIDFunc(f func() string) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ProviderID = f
	})
}

// Clear any values for the column
func (m assetMods) UnsetProviderID() AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ProviderID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m assetMods) RandomProviderID(f *faker.Faker) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.ProviderID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m assetMods) AssetID(val null.Val[int32]) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.AssetID = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m assetMods) AssetIDFunc(f func() null.Val[int32]) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.AssetID = f
	})
}

// Clear any values for the column
func (m assetMods) UnsetAssetID() AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.AssetID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m assetMods) RandomAssetID(f *faker.Faker) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.AssetID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			if f.Bool() {
				return null.FromPtr[int32](nil)
			}

			return null.From(random_int32(f))
		}
	})
}

func (m assetMods) WithConfiguration(rel *ConfigurationTemplate) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.r.Configuration = &assetRConfigurationR{
			o: rel,
		}
	})
}

func (m assetMods) WithNewConfiguration(mods ...ConfigurationMod) AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		related := o.f.NewConfiguration(mods...)

		m.WithConfiguration(related).Apply(o)
	})
}

func (m assetMods) WithoutConfiguration() AssetMod {
	return AssetModFunc(func(o *AssetTemplate) {
		o.r.Configuration = nil
	})
}
