// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

type Factory struct {
	baseAssetMods         AssetModSlice
	baseConfigurationMods ConfigurationModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewAsset(mods ...AssetMod) *AssetTemplate {
	o := &AssetTemplate{f: f}

	if f != nil {
		f.baseAssetMods.Apply(o)
	}

	AssetModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewConfiguration(mods ...ConfigurationMod) *ConfigurationTemplate {
	o := &ConfigurationTemplate{f: f}

	if f != nil {
		f.baseConfigurationMods.Apply(o)
	}

	ConfigurationModSlice(mods).Apply(o)

	return o
}

func (f *Factory) ClearBaseAssetMods() {
	f.baseAssetMods = nil
}

func (f *Factory) AddBaseAssetMod(mods ...AssetMod) {
	f.baseAssetMods = append(f.baseAssetMods, mods...)
}

func (f *Factory) ClearBaseConfigurationMods() {
	f.baseConfigurationMods = nil
}

func (f *Factory) AddBaseConfigurationMod(mods ...ConfigurationMod) {
	f.baseConfigurationMods = append(f.baseConfigurationMods, mods...)
}
