// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/jaswdr/faker/v2"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob/types"
)

var defaultFaker = faker.New()

func random_bool(f *faker.Faker) bool {
	if f == nil {
		f = &defaultFaker
	}

	return f.Bool()
}

func random_int32(f *faker.Faker) int32 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int32()
}

func random_int64(f *faker.Faker) int64 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int64()
}

func random_pq_StringArray(f *faker.Faker) pq.StringArray {
	if f == nil {
		f = &defaultFaker
	}

	arr := make(pq.StringArray, f.IntBetween(1, 5))
	for i := range arr {
		arr[i] = random_string(f)
	}
	return arr
}

func random_string(f *faker.Faker) string {
	if f == nil {
		f = &defaultFaker
	}

	return strings.Join(f.Lorem().Words(f.IntBetween(1, 5)), " ")
}

func random_types_JSON_json_RawMessage_(f *faker.Faker) types.JSON[json.RawMessage] {
	if f == nil {
		f = &defaultFaker
	}

	s := &bytes.Buffer{}
	s.WriteRune('{')
	for i := 0; i < f.IntBetween(1, 5); i++ {
		if i > 0 {
			fmt.Fprint(s, ", ")
		}
		fmt.Fprintf(s, "%q:%q", f.Lorem().Word(), f.Lorem().Word())
	}
	s.WriteRune('}')
	return types.NewJSON[json.RawMessage](s.Bytes())
}
