// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"

	models "app-name/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type ConfigurationMod interface {
	Apply(*ConfigurationTemplate)
}

type ConfigurationModFunc func(*ConfigurationTemplate)

func (f ConfigurationModFunc) Apply(n *ConfigurationTemplate) {
	f(n)
}

type ConfigurationModSlice []ConfigurationMod

func (mods ConfigurationModSlice) Apply(n *ConfigurationTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// ConfigurationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ConfigurationTemplate struct {
	ID                func() int64
	APIAccessChangeMe func() string
	RefreshInterval   func() int32
	RequestTimeout    func() int32
	AssetFilter       func() types.JSON[json.RawMessage]
	Active            func() bool
	Enable            func() bool
	ProjectIds        func() pq.StringArray
	UserID            func() string

	r configurationR
	f *Factory
}

type configurationR struct {
	Assets []*configurationRAssetsR
}

type configurationRAssetsR struct {
	number int
	o      *AssetTemplate
}

// Apply mods to the ConfigurationTemplate
func (o *ConfigurationTemplate) Apply(mods ...ConfigurationMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.Configuration
// this does nothing with the relationship templates
func (o ConfigurationTemplate) toModel() *models.Configuration {
	m := &models.Configuration{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.APIAccessChangeMe != nil {
		m.APIAccessChangeMe = o.APIAccessChangeMe()
	}
	if o.RefreshInterval != nil {
		m.RefreshInterval = o.RefreshInterval()
	}
	if o.RequestTimeout != nil {
		m.RequestTimeout = o.RequestTimeout()
	}
	if o.AssetFilter != nil {
		m.AssetFilter = o.AssetFilter()
	}
	if o.Active != nil {
		m.Active = o.Active()
	}
	if o.Enable != nil {
		m.Enable = o.Enable()
	}
	if o.ProjectIds != nil {
		m.ProjectIds = o.ProjectIds()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}

	return m
}

// toModels returns an models.ConfigurationSlice
// this does nothing with the relationship templates
func (o ConfigurationTemplate) toModels(number int) models.ConfigurationSlice {
	m := make(models.ConfigurationSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.Configuration
// according to the relationships in the template. Nothing is inserted into the db
func (t ConfigurationTemplate) setModelRels(o *models.Configuration) {
	if t.r.Assets != nil {
		rel := models.AssetSlice{}
		for _, r := range t.r.Assets {
			related := r.o.toModels(r.number)
			for _, rel := range related {
				rel.ConfigurationID = o.ID
				rel.R.Configuration = o
			}
			rel = append(rel, related...)
		}
		o.R.Assets = rel
	}
}

// BuildSetter returns an *models.ConfigurationSetter
// this does nothing with the relationship templates
func (o ConfigurationTemplate) BuildSetter() *models.ConfigurationSetter {
	m := &models.ConfigurationSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.APIAccessChangeMe != nil {
		m.APIAccessChangeMe = omit.From(o.APIAccessChangeMe())
	}
	if o.RefreshInterval != nil {
		m.RefreshInterval = omit.From(o.RefreshInterval())
	}
	if o.RequestTimeout != nil {
		m.RequestTimeout = omit.From(o.RequestTimeout())
	}
	if o.AssetFilter != nil {
		m.AssetFilter = omit.From(o.AssetFilter())
	}
	if o.Active != nil {
		m.Active = omit.From(o.Active())
	}
	if o.Enable != nil {
		m.Enable = omit.From(o.Enable())
	}
	if o.ProjectIds != nil {
		m.ProjectIds = omit.From(o.ProjectIds())
	}
	if o.UserID != nil {
		m.UserID = omit.From(o.UserID())
	}

	return m
}

// BuildManySetter returns an []*models.ConfigurationSetter
// this does nothing with the relationship templates
func (o ConfigurationTemplate) BuildManySetter(number int) []*models.ConfigurationSetter {
	m := make([]*models.ConfigurationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Configuration
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConfigurationTemplate.Create
func (o ConfigurationTemplate) Build() *models.Configuration {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ConfigurationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConfigurationTemplate.CreateMany
func (o ConfigurationTemplate) BuildMany(number int) models.ConfigurationSlice {
	m := make(models.ConfigurationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableConfiguration(m *models.ConfigurationSetter) {
	if m.APIAccessChangeMe.IsUnset() {
		m.APIAccessChangeMe = omit.From(random_string(nil))
	}
	if m.AssetFilter.IsUnset() {
		m.AssetFilter = omit.From(random_types_JSON_json_RawMessage_(nil))
	}
	if m.ProjectIds.IsUnset() {
		m.ProjectIds = omit.From(random_pq_StringArray(nil))
	}
	if m.UserID.IsUnset() {
		m.UserID = omit.From(random_string(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Configuration
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ConfigurationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Configuration) (context.Context, error) {
	var err error

	if o.r.Assets != nil {
		for _, r := range o.r.Assets {
			var rel0 models.AssetSlice
			ctx, rel0, err = r.o.createMany(ctx, exec, r.number)
			if err != nil {
				return ctx, err
			}

			err = m.AttachAssets(ctx, exec, rel0...)
			if err != nil {
				return ctx, err
			}
		}
	}

	return ctx, err
}

// Create builds a configuration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ConfigurationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Configuration, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a configuration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ConfigurationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Configuration {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a configuration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ConfigurationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Configuration {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a configuration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *ConfigurationTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.Configuration, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableConfiguration(opt)

	m, err := models.Configurations.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = configurationCtx.WithValue(ctx, m)

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple configurations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ConfigurationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ConfigurationSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple configurations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ConfigurationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ConfigurationSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple configurations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ConfigurationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ConfigurationSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple configurations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o ConfigurationTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.ConfigurationSlice, error) {
	var err error
	m := make(models.ConfigurationSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// Configuration has methods that act as mods for the ConfigurationTemplate
var ConfigurationMods configurationMods

type configurationMods struct{}

func (m configurationMods) RandomizeAllColumns(f *faker.Faker) ConfigurationMod {
	return ConfigurationModSlice{
		ConfigurationMods.RandomID(f),
		ConfigurationMods.RandomAPIAccessChangeMe(f),
		ConfigurationMods.RandomRefreshInterval(f),
		ConfigurationMods.RandomRequestTimeout(f),
		ConfigurationMods.RandomAssetFilter(f),
		ConfigurationMods.RandomActive(f),
		ConfigurationMods.RandomEnable(f),
		ConfigurationMods.RandomProjectIds(f),
		ConfigurationMods.RandomUserID(f),
	}
}

// Set the model columns to this value
func (m configurationMods) ID(val int64) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m configurationMods) IDFunc(f func() int64) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetID() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomID(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m configurationMods) APIAccessChangeMe(val string) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.APIAccessChangeMe = func() string { return val }
	})
}

// Set the Column from the function
func (m configurationMods) APIAccessChangeMeFunc(f func() string) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.APIAccessChangeMe = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetAPIAccessChangeMe() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.APIAccessChangeMe = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomAPIAccessChangeMe(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.APIAccessChangeMe = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m configurationMods) RefreshInterval(val int32) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.RefreshInterval = func() int32 { return val }
	})
}

// Set the Column from the function
func (m configurationMods) RefreshIntervalFunc(f func() int32) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.RefreshInterval = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetRefreshInterval() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.RefreshInterval = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomRefreshInterval(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.RefreshInterval = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m configurationMods) RequestTimeout(val int32) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.RequestTimeout = func() int32 { return val }
	})
}

// Set the Column from the function
func (m configurationMods) RequestTimeoutFunc(f func() int32) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.RequestTimeout = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetRequestTimeout() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.RequestTimeout = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomRequestTimeout(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.RequestTimeout = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m configurationMods) AssetFilter(val types.JSON[json.RawMessage]) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.AssetFilter = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m configurationMods) AssetFilterFunc(f func() types.JSON[json.RawMessage]) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.AssetFilter = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetAssetFilter() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.AssetFilter = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomAssetFilter(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.AssetFilter = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m configurationMods) Active(val bool) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.Active = func() bool { return val }
	})
}

// Set the Column from the function
func (m configurationMods) ActiveFunc(f func() bool) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.Active = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetActive() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.Active = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomActive(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.Active = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m configurationMods) Enable(val bool) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.Enable = func() bool { return val }
	})
}

// Set the Column from the function
func (m configurationMods) EnableFunc(f func() bool) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.Enable = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetEnable() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.Enable = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomEnable(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.Enable = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m configurationMods) ProjectIds(val pq.StringArray) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.ProjectIds = func() pq.StringArray { return val }
	})
}

// Set the Column from the function
func (m configurationMods) ProjectIdsFunc(f func() pq.StringArray) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.ProjectIds = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetProjectIds() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.ProjectIds = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomProjectIds(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.ProjectIds = func() pq.StringArray {
			return random_pq_StringArray(f)
		}
	})
}

// Set the model columns to this value
func (m configurationMods) UserID(val string) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m configurationMods) UserIDFunc(f func() string) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m configurationMods) UnsetUserID() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m configurationMods) RandomUserID(f *faker.Faker) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.UserID = func() string {
			return random_string(f)
		}
	})
}

func (m configurationMods) WithAssets(number int, related *AssetTemplate) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.r.Assets = []*configurationRAssetsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m configurationMods) WithNewAssets(number int, mods ...AssetMod) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		related := o.f.NewAsset(mods...)
		m.WithAssets(number, related).Apply(o)
	})
}

func (m configurationMods) AddAssets(number int, related *AssetTemplate) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.r.Assets = append(o.r.Assets, &configurationRAssetsR{
			number: number,
			o:      related,
		})
	})
}

func (m configurationMods) AddNewAssets(number int, mods ...AssetMod) ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		related := o.f.NewAsset(mods...)
		m.AddAssets(number, related).Apply(o)
	})
}

func (m configurationMods) WithoutAssets() ConfigurationMod {
	return ConfigurationModFunc(func(o *ConfigurationTemplate) {
		o.r.Assets = nil
	})
}
