// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Asset is an object representing the database table.
type Asset struct {
	ID              int64           `db:"id,pk" `
	ConfigurationID int64           `db:"configuration_id" `
	ProjectID       string          `db:"project_id" `
	GlobalAssetID   string          `db:"global_asset_id" `
	ProviderID      string          `db:"provider_id" `
	AssetID         null.Val[int32] `db:"asset_id" `

	R assetR `db:"-" `
}

// AssetSlice is an alias for a slice of pointers to Asset.
// This should almost always be used instead of []*Asset.
type AssetSlice []*Asset

// Assets contains methods to work with the asset table
var Assets = psql.NewTablex[*Asset, AssetSlice, *AssetSetter]("", "asset")

// AssetsQuery is a query on the asset table
type AssetsQuery = *psql.ViewQuery[*Asset, AssetSlice]

// assetR is where relationships are stored.
type assetR struct {
	Configuration *Configuration // asset.asset_configuration_id_fkey
}

type assetColumnNames struct {
	ID              string
	ConfigurationID string
	ProjectID       string
	GlobalAssetID   string
	ProviderID      string
	AssetID         string
}

var AssetColumns = buildAssetColumns("asset")

type assetColumns struct {
	tableAlias      string
	ID              psql.Expression
	ConfigurationID psql.Expression
	ProjectID       psql.Expression
	GlobalAssetID   psql.Expression
	ProviderID      psql.Expression
	AssetID         psql.Expression
}

func (c assetColumns) Alias() string {
	return c.tableAlias
}

func (assetColumns) AliasedAs(alias string) assetColumns {
	return buildAssetColumns(alias)
}

func buildAssetColumns(alias string) assetColumns {
	return assetColumns{
		tableAlias:      alias,
		ID:              psql.Quote(alias, "id"),
		ConfigurationID: psql.Quote(alias, "configuration_id"),
		ProjectID:       psql.Quote(alias, "project_id"),
		GlobalAssetID:   psql.Quote(alias, "global_asset_id"),
		ProviderID:      psql.Quote(alias, "provider_id"),
		AssetID:         psql.Quote(alias, "asset_id"),
	}
}

type assetWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, int64]
	ConfigurationID psql.WhereMod[Q, int64]
	ProjectID       psql.WhereMod[Q, string]
	GlobalAssetID   psql.WhereMod[Q, string]
	ProviderID      psql.WhereMod[Q, string]
	AssetID         psql.WhereNullMod[Q, int32]
}

func (assetWhere[Q]) AliasedAs(alias string) assetWhere[Q] {
	return buildAssetWhere[Q](buildAssetColumns(alias))
}

func buildAssetWhere[Q psql.Filterable](cols assetColumns) assetWhere[Q] {
	return assetWhere[Q]{
		ID:              psql.Where[Q, int64](cols.ID),
		ConfigurationID: psql.Where[Q, int64](cols.ConfigurationID),
		ProjectID:       psql.Where[Q, string](cols.ProjectID),
		GlobalAssetID:   psql.Where[Q, string](cols.GlobalAssetID),
		ProviderID:      psql.Where[Q, string](cols.ProviderID),
		AssetID:         psql.WhereNull[Q, int32](cols.AssetID),
	}
}

// AssetSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AssetSetter struct {
	ID              omit.Val[int64]     `db:"id,pk" `
	ConfigurationID omit.Val[int64]     `db:"configuration_id" `
	ProjectID       omit.Val[string]    `db:"project_id" `
	GlobalAssetID   omit.Val[string]    `db:"global_asset_id" `
	ProviderID      omit.Val[string]    `db:"provider_id" `
	AssetID         omitnull.Val[int32] `db:"asset_id" `
}

func (s AssetSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.ConfigurationID.IsUnset() {
		vals = append(vals, "configuration_id")
	}

	if !s.ProjectID.IsUnset() {
		vals = append(vals, "project_id")
	}

	if !s.GlobalAssetID.IsUnset() {
		vals = append(vals, "global_asset_id")
	}

	if !s.ProviderID.IsUnset() {
		vals = append(vals, "provider_id")
	}

	if !s.AssetID.IsUnset() {
		vals = append(vals, "asset_id")
	}

	return vals
}

func (s AssetSetter) Overwrite(t *Asset) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.ConfigurationID.IsUnset() {
		t.ConfigurationID, _ = s.ConfigurationID.Get()
	}
	if !s.ProjectID.IsUnset() {
		t.ProjectID, _ = s.ProjectID.Get()
	}
	if !s.GlobalAssetID.IsUnset() {
		t.GlobalAssetID, _ = s.GlobalAssetID.Get()
	}
	if !s.ProviderID.IsUnset() {
		t.ProviderID, _ = s.ProviderID.Get()
	}
	if !s.AssetID.IsUnset() {
		t.AssetID, _ = s.AssetID.GetNull()
	}
}

func (s *AssetSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Assets.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsUnset() {
			vals[0] = psql.Raw("DEFAULT")
		} else {
			vals[0] = psql.Arg(s.ID)
		}

		if s.ConfigurationID.IsUnset() {
			vals[1] = psql.Raw("DEFAULT")
		} else {
			vals[1] = psql.Arg(s.ConfigurationID)
		}

		if s.ProjectID.IsUnset() {
			vals[2] = psql.Raw("DEFAULT")
		} else {
			vals[2] = psql.Arg(s.ProjectID)
		}

		if s.GlobalAssetID.IsUnset() {
			vals[3] = psql.Raw("DEFAULT")
		} else {
			vals[3] = psql.Arg(s.GlobalAssetID)
		}

		if s.ProviderID.IsUnset() {
			vals[4] = psql.Raw("DEFAULT")
		} else {
			vals[4] = psql.Arg(s.ProviderID)
		}

		if s.AssetID.IsUnset() {
			vals[5] = psql.Raw("DEFAULT")
		} else {
			vals[5] = psql.Arg(s.AssetID)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AssetSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AssetSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.ConfigurationID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "configuration_id")...),
			psql.Arg(s.ConfigurationID),
		}})
	}

	if !s.ProjectID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "project_id")...),
			psql.Arg(s.ProjectID),
		}})
	}

	if !s.GlobalAssetID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "global_asset_id")...),
			psql.Arg(s.GlobalAssetID),
		}})
	}

	if !s.ProviderID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "provider_id")...),
			psql.Arg(s.ProviderID),
		}})
	}

	if !s.AssetID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "asset_id")...),
			psql.Arg(s.AssetID),
		}})
	}

	return exprs
}

// FindAsset retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAsset(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Asset, error) {
	if len(cols) == 0 {
		return Assets.Query(
			SelectWhere.Assets.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Assets.Query(
		SelectWhere.Assets.ID.EQ(IDPK),
		sm.Columns(Assets.Columns().Only(cols...)),
	).One(ctx, exec)
}

// AssetExists checks the presence of a single record by primary key
func AssetExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Assets.Query(
		SelectWhere.Assets.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Asset is retrieved from the database
func (o *Asset) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Assets.AfterSelectHooks.RunHooks(ctx, exec, AssetSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Assets.AfterInsertHooks.RunHooks(ctx, exec, AssetSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Assets.AfterUpdateHooks.RunHooks(ctx, exec, AssetSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Assets.AfterDeleteHooks.RunHooks(ctx, exec, AssetSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the Asset
func (o *Asset) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Asset) pkEQ() dialect.Expression {
	return psql.Quote("asset", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Asset
func (o *Asset) Update(ctx context.Context, exec bob.Executor, s *AssetSetter) error {
	v, err := Assets.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Asset record with an executor
func (o *Asset) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Assets.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Asset using the executor
func (o *Asset) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Assets.Query(
		SelectWhere.Assets.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AssetSlice is retrieved from the database
func (o AssetSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Assets.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Assets.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Assets.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Assets.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AssetSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("asset", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AssetSlice) copyMatchingRows(from ...*Asset) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AssetSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Assets.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Asset:
				o.copyMatchingRows(retrieved)
			case []*Asset:
				o.copyMatchingRows(retrieved...)
			case AssetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Asset or a slice of Asset
				// then run the AfterUpdateHooks on the slice
				_, err = Assets.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AssetSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Assets.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Asset:
				o.copyMatchingRows(retrieved)
			case []*Asset:
				o.copyMatchingRows(retrieved...)
			case AssetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Asset or a slice of Asset
				// then run the AfterDeleteHooks on the slice
				_, err = Assets.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AssetSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AssetSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Assets.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AssetSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Assets.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AssetSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Assets.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type assetJoins[Q dialect.Joinable] struct {
	typ           string
	Configuration func(context.Context) modAs[Q, configurationColumns]
}

func (j assetJoins[Q]) aliasedAs(alias string) assetJoins[Q] {
	return buildAssetJoins[Q](buildAssetColumns(alias), j.typ)
}

func buildAssetJoins[Q dialect.Joinable](cols assetColumns, typ string) assetJoins[Q] {
	return assetJoins[Q]{
		typ:           typ,
		Configuration: assetsJoinConfiguration[Q](cols, typ),
	}
}

func assetsJoinConfiguration[Q dialect.Joinable](from assetColumns, typ string) func(context.Context) modAs[Q, configurationColumns] {
	return func(ctx context.Context) modAs[Q, configurationColumns] {
		return modAs[Q, configurationColumns]{
			c: ConfigurationColumns,
			f: func(to configurationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Configurations.Name().As(to.Alias())).On(
						to.ID.EQ(from.ConfigurationID),
					))
				}

				return mods
			},
		}
	}
}

// Configuration starts a query for related objects on configuration
func (o *Asset) Configuration(mods ...bob.Mod[*dialect.SelectQuery]) ConfigurationsQuery {
	return Configurations.Query(append(mods,
		sm.Where(ConfigurationColumns.ID.EQ(psql.Arg(o.ConfigurationID))),
	)...)
}

func (os AssetSlice) Configuration(mods ...bob.Mod[*dialect.SelectQuery]) ConfigurationsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.ConfigurationID)
	}

	return Configurations.Query(append(mods,
		sm.Where(psql.Group(ConfigurationColumns.ID).In(PKArgs...)),
	)...)
}

func (o *Asset) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Configuration":
		rel, ok := retrieved.(*Configuration)
		if !ok {
			return fmt.Errorf("asset cannot load %T as %q", retrieved, name)
		}

		o.R.Configuration = rel

		if rel != nil {
			rel.R.Assets = AssetSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("asset has no relationship %q", name)
	}
}

func PreloadAssetConfiguration(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*Configuration, ConfigurationSlice](orm.Relationship{
		Name: "Configuration",
		Sides: []orm.RelSide{
			{
				From: TableNames.Assets,
				To:   TableNames.Configurations,
				FromColumns: []string{
					ColumnNames.Assets.ConfigurationID,
				},
				ToColumns: []string{
					ColumnNames.Configurations.ID,
				},
			},
		},
	}, Configurations.Columns().Names(), opts...)
}

func ThenLoadAssetConfiguration(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadAssetConfiguration(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load AssetConfiguration", retrieved)
		}

		err := loader.LoadAssetConfiguration(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadAssetConfiguration loads the asset's Configuration into the .R struct
func (o *Asset) LoadAssetConfiguration(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Configuration = nil

	related, err := o.Configuration(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Assets = AssetSlice{o}

	o.R.Configuration = related
	return nil
}

// LoadAssetConfiguration loads the asset's Configuration into the .R struct
func (os AssetSlice) LoadAssetConfiguration(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	configurations, err := os.Configuration(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range configurations {
			if o.ConfigurationID != rel.ID {
				continue
			}

			rel.R.Assets = append(rel.R.Assets, o)

			o.R.Configuration = rel
			break
		}
	}

	return nil
}

func attachAssetConfiguration0(ctx context.Context, exec bob.Executor, count int, asset0 *Asset, configuration1 *Configuration) (*Asset, error) {
	setter := &AssetSetter{
		ConfigurationID: omit.From(configuration1.ID),
	}

	err := asset0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAssetConfiguration0: %w", err)
	}

	return asset0, nil
}

func (asset0 *Asset) InsertConfiguration(ctx context.Context, exec bob.Executor, related *ConfigurationSetter) error {
	configuration1, err := Configurations.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAssetConfiguration0(ctx, exec, 1, asset0, configuration1)
	if err != nil {
		return err
	}

	asset0.R.Configuration = configuration1

	configuration1.R.Assets = append(configuration1.R.Assets, asset0)

	return nil
}

func (asset0 *Asset) AttachConfiguration(ctx context.Context, exec bob.Executor, configuration1 *Configuration) error {
	var err error

	_, err = attachAssetConfiguration0(ctx, exec, 1, asset0, configuration1)
	if err != nil {
		return err
	}

	asset0.R.Configuration = configuration1

	configuration1.R.Assets = append(configuration1.R.Assets, asset0)

	return nil
}
