// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"

	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Make sure the type Asset runs hooks after queries
var _ bob.HookableType = &Asset{}

// Make sure the type Configuration runs hooks after queries
var _ bob.HookableType = &Configuration{}

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[json.RawMessage])(nil)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[json.RawMessage])

// Make sure the type pq.StringArray satisfies database/sql.Scanner
var _ sql.Scanner = (*pq.StringArray)(nil)

// Make sure the type pq.StringArray satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(pq.StringArray)
