// Code generated by BobGen psql v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/types"
)

// Configuration is an object representing the database table.
type Configuration struct {
	ID                int64                       `db:"id,pk" `
	APIAccessChangeMe string                      `db:"api_access_change_me" `
	RefreshInterval   int32                       `db:"refresh_interval" `
	RequestTimeout    int32                       `db:"request_timeout" `
	AssetFilter       types.JSON[json.RawMessage] `db:"asset_filter" `
	Active            bool                        `db:"active" `
	Enable            bool                        `db:"enable" `
	ProjectIds        pq.StringArray              `db:"project_ids" `
	UserID            string                      `db:"user_id" `

	R configurationR `db:"-" `
}

// ConfigurationSlice is an alias for a slice of pointers to Configuration.
// This should almost always be used instead of []*Configuration.
type ConfigurationSlice []*Configuration

// Configurations contains methods to work with the configuration table
var Configurations = psql.NewTablex[*Configuration, ConfigurationSlice, *ConfigurationSetter]("", "configuration")

// ConfigurationsQuery is a query on the configuration table
type ConfigurationsQuery = *psql.ViewQuery[*Configuration, ConfigurationSlice]

// configurationR is where relationships are stored.
type configurationR struct {
	Assets AssetSlice // asset.asset_configuration_id_fkey
}

type configurationColumnNames struct {
	ID                string
	APIAccessChangeMe string
	RefreshInterval   string
	RequestTimeout    string
	AssetFilter       string
	Active            string
	Enable            string
	ProjectIds        string
	UserID            string
}

var ConfigurationColumns = buildConfigurationColumns("configuration")

type configurationColumns struct {
	tableAlias        string
	ID                psql.Expression
	APIAccessChangeMe psql.Expression
	RefreshInterval   psql.Expression
	RequestTimeout    psql.Expression
	AssetFilter       psql.Expression
	Active            psql.Expression
	Enable            psql.Expression
	ProjectIds        psql.Expression
	UserID            psql.Expression
}

func (c configurationColumns) Alias() string {
	return c.tableAlias
}

func (configurationColumns) AliasedAs(alias string) configurationColumns {
	return buildConfigurationColumns(alias)
}

func buildConfigurationColumns(alias string) configurationColumns {
	return configurationColumns{
		tableAlias:        alias,
		ID:                psql.Quote(alias, "id"),
		APIAccessChangeMe: psql.Quote(alias, "api_access_change_me"),
		RefreshInterval:   psql.Quote(alias, "refresh_interval"),
		RequestTimeout:    psql.Quote(alias, "request_timeout"),
		AssetFilter:       psql.Quote(alias, "asset_filter"),
		Active:            psql.Quote(alias, "active"),
		Enable:            psql.Quote(alias, "enable"),
		ProjectIds:        psql.Quote(alias, "project_ids"),
		UserID:            psql.Quote(alias, "user_id"),
	}
}

type configurationWhere[Q psql.Filterable] struct {
	ID                psql.WhereMod[Q, int64]
	APIAccessChangeMe psql.WhereMod[Q, string]
	RefreshInterval   psql.WhereMod[Q, int32]
	RequestTimeout    psql.WhereMod[Q, int32]
	AssetFilter       psql.WhereMod[Q, types.JSON[json.RawMessage]]
	Active            psql.WhereMod[Q, bool]
	Enable            psql.WhereMod[Q, bool]
	ProjectIds        psql.WhereMod[Q, pq.StringArray]
	UserID            psql.WhereMod[Q, string]
}

func (configurationWhere[Q]) AliasedAs(alias string) configurationWhere[Q] {
	return buildConfigurationWhere[Q](buildConfigurationColumns(alias))
}

func buildConfigurationWhere[Q psql.Filterable](cols configurationColumns) configurationWhere[Q] {
	return configurationWhere[Q]{
		ID:                psql.Where[Q, int64](cols.ID),
		APIAccessChangeMe: psql.Where[Q, string](cols.APIAccessChangeMe),
		RefreshInterval:   psql.Where[Q, int32](cols.RefreshInterval),
		RequestTimeout:    psql.Where[Q, int32](cols.RequestTimeout),
		AssetFilter:       psql.Where[Q, types.JSON[json.RawMessage]](cols.AssetFilter),
		Active:            psql.Where[Q, bool](cols.Active),
		Enable:            psql.Where[Q, bool](cols.Enable),
		ProjectIds:        psql.Where[Q, pq.StringArray](cols.ProjectIds),
		UserID:            psql.Where[Q, string](cols.UserID),
	}
}

// ConfigurationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ConfigurationSetter struct {
	ID                omit.Val[int64]                       `db:"id,pk" `
	APIAccessChangeMe omit.Val[string]                      `db:"api_access_change_me" `
	RefreshInterval   omit.Val[int32]                       `db:"refresh_interval" `
	RequestTimeout    omit.Val[int32]                       `db:"request_timeout" `
	AssetFilter       omit.Val[types.JSON[json.RawMessage]] `db:"asset_filter" `
	Active            omit.Val[bool]                        `db:"active" `
	Enable            omit.Val[bool]                        `db:"enable" `
	ProjectIds        omit.Val[pq.StringArray]              `db:"project_ids" `
	UserID            omit.Val[string]                      `db:"user_id" `
}

func (s ConfigurationSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.APIAccessChangeMe.IsUnset() {
		vals = append(vals, "api_access_change_me")
	}

	if !s.RefreshInterval.IsUnset() {
		vals = append(vals, "refresh_interval")
	}

	if !s.RequestTimeout.IsUnset() {
		vals = append(vals, "request_timeout")
	}

	if !s.AssetFilter.IsUnset() {
		vals = append(vals, "asset_filter")
	}

	if !s.Active.IsUnset() {
		vals = append(vals, "active")
	}

	if !s.Enable.IsUnset() {
		vals = append(vals, "enable")
	}

	if !s.ProjectIds.IsUnset() {
		vals = append(vals, "project_ids")
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}

	return vals
}

func (s ConfigurationSetter) Overwrite(t *Configuration) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.APIAccessChangeMe.IsUnset() {
		t.APIAccessChangeMe, _ = s.APIAccessChangeMe.Get()
	}
	if !s.RefreshInterval.IsUnset() {
		t.RefreshInterval, _ = s.RefreshInterval.Get()
	}
	if !s.RequestTimeout.IsUnset() {
		t.RequestTimeout, _ = s.RequestTimeout.Get()
	}
	if !s.AssetFilter.IsUnset() {
		t.AssetFilter, _ = s.AssetFilter.Get()
	}
	if !s.Active.IsUnset() {
		t.Active, _ = s.Active.Get()
	}
	if !s.Enable.IsUnset() {
		t.Enable, _ = s.Enable.Get()
	}
	if !s.ProjectIds.IsUnset() {
		t.ProjectIds, _ = s.ProjectIds.Get()
	}
	if !s.UserID.IsUnset() {
		t.UserID, _ = s.UserID.Get()
	}
}

func (s *ConfigurationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Configurations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID.IsUnset() {
			vals[0] = psql.Raw("DEFAULT")
		} else {
			vals[0] = psql.Arg(s.ID)
		}

		if s.APIAccessChangeMe.IsUnset() {
			vals[1] = psql.Raw("DEFAULT")
		} else {
			vals[1] = psql.Arg(s.APIAccessChangeMe)
		}

		if s.RefreshInterval.IsUnset() {
			vals[2] = psql.Raw("DEFAULT")
		} else {
			vals[2] = psql.Arg(s.RefreshInterval)
		}

		if s.RequestTimeout.IsUnset() {
			vals[3] = psql.Raw("DEFAULT")
		} else {
			vals[3] = psql.Arg(s.RequestTimeout)
		}

		if s.AssetFilter.IsUnset() {
			vals[4] = psql.Raw("DEFAULT")
		} else {
			vals[4] = psql.Arg(s.AssetFilter)
		}

		if s.Active.IsUnset() {
			vals[5] = psql.Raw("DEFAULT")
		} else {
			vals[5] = psql.Arg(s.Active)
		}

		if s.Enable.IsUnset() {
			vals[6] = psql.Raw("DEFAULT")
		} else {
			vals[6] = psql.Arg(s.Enable)
		}

		if s.ProjectIds.IsUnset() {
			vals[7] = psql.Raw("DEFAULT")
		} else {
			vals[7] = psql.Arg(s.ProjectIds)
		}

		if s.UserID.IsUnset() {
			vals[8] = psql.Raw("DEFAULT")
		} else {
			vals[8] = psql.Arg(s.UserID)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ConfigurationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ConfigurationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.APIAccessChangeMe.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "api_access_change_me")...),
			psql.Arg(s.APIAccessChangeMe),
		}})
	}

	if !s.RefreshInterval.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "refresh_interval")...),
			psql.Arg(s.RefreshInterval),
		}})
	}

	if !s.RequestTimeout.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "request_timeout")...),
			psql.Arg(s.RequestTimeout),
		}})
	}

	if !s.AssetFilter.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "asset_filter")...),
			psql.Arg(s.AssetFilter),
		}})
	}

	if !s.Active.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "active")...),
			psql.Arg(s.Active),
		}})
	}

	if !s.Enable.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "enable")...),
			psql.Arg(s.Enable),
		}})
	}

	if !s.ProjectIds.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "project_ids")...),
			psql.Arg(s.ProjectIds),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	return exprs
}

// FindConfiguration retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindConfiguration(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Configuration, error) {
	if len(cols) == 0 {
		return Configurations.Query(
			SelectWhere.Configurations.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Configurations.Query(
		SelectWhere.Configurations.ID.EQ(IDPK),
		sm.Columns(Configurations.Columns().Only(cols...)),
	).One(ctx, exec)
}

// ConfigurationExists checks the presence of a single record by primary key
func ConfigurationExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Configurations.Query(
		SelectWhere.Configurations.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Configuration is retrieved from the database
func (o *Configuration) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Configurations.AfterSelectHooks.RunHooks(ctx, exec, ConfigurationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Configurations.AfterInsertHooks.RunHooks(ctx, exec, ConfigurationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Configurations.AfterUpdateHooks.RunHooks(ctx, exec, ConfigurationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Configurations.AfterDeleteHooks.RunHooks(ctx, exec, ConfigurationSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the Configuration
func (o *Configuration) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Configuration) pkEQ() dialect.Expression {
	return psql.Quote("configuration", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Configuration
func (o *Configuration) Update(ctx context.Context, exec bob.Executor, s *ConfigurationSetter) error {
	v, err := Configurations.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Configuration record with an executor
func (o *Configuration) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Configurations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Configuration using the executor
func (o *Configuration) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Configurations.Query(
		SelectWhere.Configurations.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ConfigurationSlice is retrieved from the database
func (o ConfigurationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Configurations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Configurations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Configurations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Configurations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ConfigurationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("configuration", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ConfigurationSlice) copyMatchingRows(from ...*Configuration) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ConfigurationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Configurations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Configuration:
				o.copyMatchingRows(retrieved)
			case []*Configuration:
				o.copyMatchingRows(retrieved...)
			case ConfigurationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Configuration or a slice of Configuration
				// then run the AfterUpdateHooks on the slice
				_, err = Configurations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ConfigurationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Configurations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Configuration:
				o.copyMatchingRows(retrieved)
			case []*Configuration:
				o.copyMatchingRows(retrieved...)
			case ConfigurationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Configuration or a slice of Configuration
				// then run the AfterDeleteHooks on the slice
				_, err = Configurations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ConfigurationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ConfigurationSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Configurations.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ConfigurationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Configurations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ConfigurationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Configurations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type configurationJoins[Q dialect.Joinable] struct {
	typ    string
	Assets func(context.Context) modAs[Q, assetColumns]
}

func (j configurationJoins[Q]) aliasedAs(alias string) configurationJoins[Q] {
	return buildConfigurationJoins[Q](buildConfigurationColumns(alias), j.typ)
}

func buildConfigurationJoins[Q dialect.Joinable](cols configurationColumns, typ string) configurationJoins[Q] {
	return configurationJoins[Q]{
		typ:    typ,
		Assets: configurationsJoinAssets[Q](cols, typ),
	}
}

func configurationsJoinAssets[Q dialect.Joinable](from configurationColumns, typ string) func(context.Context) modAs[Q, assetColumns] {
	return func(ctx context.Context) modAs[Q, assetColumns] {
		return modAs[Q, assetColumns]{
			c: AssetColumns,
			f: func(to assetColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Assets.Name().As(to.Alias())).On(
						to.ConfigurationID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

// Assets starts a query for related objects on asset
func (o *Configuration) Assets(mods ...bob.Mod[*dialect.SelectQuery]) AssetsQuery {
	return Assets.Query(append(mods,
		sm.Where(AssetColumns.ConfigurationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ConfigurationSlice) Assets(mods ...bob.Mod[*dialect.SelectQuery]) AssetsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.ID)
	}

	return Assets.Query(append(mods,
		sm.Where(psql.Group(AssetColumns.ConfigurationID).In(PKArgs...)),
	)...)
}

func (o *Configuration) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Assets":
		rels, ok := retrieved.(AssetSlice)
		if !ok {
			return fmt.Errorf("configuration cannot load %T as %q", retrieved, name)
		}

		o.R.Assets = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Configuration = o
			}
		}
		return nil
	default:
		return fmt.Errorf("configuration has no relationship %q", name)
	}
}

func ThenLoadConfigurationAssets(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadConfigurationAssets(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load ConfigurationAssets", retrieved)
		}

		err := loader.LoadConfigurationAssets(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadConfigurationAssets loads the configuration's Assets into the .R struct
func (o *Configuration) LoadConfigurationAssets(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Assets = nil

	related, err := o.Assets(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Configuration = o
	}

	o.R.Assets = related
	return nil
}

// LoadConfigurationAssets loads the configuration's Assets into the .R struct
func (os ConfigurationSlice) LoadConfigurationAssets(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	assets, err := os.Assets(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Assets = nil
	}

	for _, o := range os {
		for _, rel := range assets {
			if o.ID != rel.ConfigurationID {
				continue
			}

			rel.R.Configuration = o

			o.R.Assets = append(o.R.Assets, rel)
		}
	}

	return nil
}

func insertConfigurationAssets0(ctx context.Context, exec bob.Executor, assets1 []*AssetSetter, configuration0 *Configuration) (AssetSlice, error) {
	for i := range assets1 {
		assets1[i].ConfigurationID = omit.From(configuration0.ID)
	}

	ret, err := Assets.Insert(bob.ToMods(assets1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertConfigurationAssets0: %w", err)
	}

	return ret, nil
}

func attachConfigurationAssets0(ctx context.Context, exec bob.Executor, count int, assets1 AssetSlice, configuration0 *Configuration) (AssetSlice, error) {
	setter := &AssetSetter{
		ConfigurationID: omit.From(configuration0.ID),
	}

	err := assets1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachConfigurationAssets0: %w", err)
	}

	return assets1, nil
}

func (configuration0 *Configuration) InsertAssets(ctx context.Context, exec bob.Executor, related ...*AssetSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	assets1, err := insertConfigurationAssets0(ctx, exec, related, configuration0)
	if err != nil {
		return err
	}

	configuration0.R.Assets = append(configuration0.R.Assets, assets1...)

	for _, rel := range assets1 {
		rel.R.Configuration = configuration0
	}
	return nil
}

func (configuration0 *Configuration) AttachAssets(ctx context.Context, exec bob.Executor, related ...*Asset) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	assets1 := AssetSlice(related)

	_, err = attachConfigurationAssets0(ctx, exec, len(related), assets1, configuration0)
	if err != nil {
		return err
	}

	configuration0.R.Assets = append(configuration0.R.Assets, assets1...)

	for _, rel := range related {
		rel.R.Configuration = configuration0
	}

	return nil
}
